In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
standings_url = "https://fbref.com/en/comps/9/Premier-League-Stats"

In [3]:
data = requests.get(standings_url)

In [4]:
data

In [5]:
daa = data

In [6]:
soup = BeautifulSoup(data.text)
standings_table = soup.select('table.stats_table')[0]
links = standings_table.find_all('a')
links = [l.get("href") for l in links]
links = [l for l in links if '/squads/' in l]

In [7]:
team_urls = [f'https://fbref.com{l}' for l in links]
team_urls

['https://fbref.com/en/squads/18bb7c10/Arsenal-Stats',
 'https://fbref.com/en/squads/b8fd03ef/Manchester-City-Stats',
 'https://fbref.com/en/squads/b2b47a98/Newcastle-United-Stats',
 'https://fbref.com/en/squads/19538871/Manchester-United-Stats',
 'https://fbref.com/en/squads/361ca564/Tottenham-Hotspur-Stats',
 'https://fbref.com/en/squads/8602292d/Aston-Villa-Stats',
 'https://fbref.com/en/squads/d07537b9/Brighton-and-Hove-Albion-Stats',
 'https://fbref.com/en/squads/822bd0ba/Liverpool-Stats',
 'https://fbref.com/en/squads/cd051869/Brentford-Stats',
 'https://fbref.com/en/squads/fd962109/Fulham-Stats',
 'https://fbref.com/en/squads/cff3d9bb/Chelsea-Stats',
 'https://fbref.com/en/squads/8cec06e1/Wolverhampton-Wanderers-Stats',
 'https://fbref.com/en/squads/7c21e445/West-Ham-United-Stats',
 'https://fbref.com/en/squads/47c64c55/Crystal-Palace-Stats',
 'https://fbref.com/en/squads/4ba7cbea/Bournemouth-Stats',
 'https://fbref.com/en/squads/5bfb9659/Leeds-United-Stats',
 'https://fbref.com/en/squads/d3fd31cc/Everton-Stats',
 'https://fbref.com/en/squads/e4a775cb/Nottingham-Forest-Stats',
 'https://fbref.com/en/squads/a2d435b3/Leicester-City-Stats',
 'https://fbref.com/en/squads/33c895d4/Southampton-Stats']

In [8]:
data = requests.get(team_urls[0])

In [9]:
matches = pd.read_html(data.text, match="Scores & Fixtures")[0]

In [10]:
soup = BeautifulSoup(data.text)
links = soup.find_all('a')
links = [l.get("href") for l in links]
links = [l for l in links if l and 'all_comps/shooting/' in l]

In [11]:
data = requests.get(f"https://fbref.com{links[0]}")

In [12]:
shooting = pd.read_html(data.text, match="Shooting")[0]

In [13]:
shooting.head()

  For Arsenal                                                              \
         Date   Time            Comp        Round  Day Venue Result GF GA
0  2022-08-05  20:00  Premier League  Matchweek 1  Fri  Away      W  2  0
1  2022-08-13  15:00  Premier League  Matchweek 2  Sat  Home      W  4  2
2  2022-08-20  17:30  Premier League  Matchweek 3  Sat  Away      W  3  0
3  2022-08-27  17:30  Premier League  Matchweek 4  Sat  Home      W  2  1
4  2022-08-31  19:30  Premier League  Matchweek 5  Wed  Home      W  2  1

                   ... Standard               Expected                    \
         Opponent  ...     Dist   FK PK PKatt       xG npxG npxG/Sh G-xG
0  Crystal Palace  ...     14.6  1.0  0     0      1.0  1.0    0.10  0.0
1  Leicester City  ...     13.0  0.0  0     0      2.7  2.7    0.16  1.3
2     Bournemouth  ...     14.8  0.0  0     0      1.3  1.3    0.10  1.7
3          Fulham  ...     15.5  1.0  0     0      2.6  2.6    0.12 -0.6
4     Aston Villa  ...     16.3  1.0  0     0      2.4  2.4    0.12 -0.4

          Unnamed: 25_level_0
  np:G-xG        Match Report
0     0.0        Match Report
1     1.3        Match Report
2     1.7        Match Report
3    -0.6        Match Report
4    -0.4        Match Report

[5 rows x 26 columns]

In [14]:
shooting.columns = shooting.columns.droplevel()

In [15]:
team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "FK", "PK", "PKatt"]], on="Date")

In [16]:
team_data.head()

,Date,Time,Comp,Round,Day,Venue,Result,GF,GA,Opponent,...,Formation,Referee,Match Report,Notes,Sh,SoT,Dist,FK,PK,PKatt
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2,0,Crystal Palace,...,4-3-3,Anthony Taylor,Match Report,NaN,10,2,14.6,1.0,0,0
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,2,Leicester City,...,4-3-3,Darren England,Match Report,NaN,19,7,13.0,0.0,0,0
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3,0,Bournemouth,...,4-3-3,Craig Pawson,Match Report,NaN,14,6,14.8,0.0,0,0
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2,1,Fulham,...,4-3-3,Jarred Gillett,Match Report,NaN,22,8,15.5,1.0,0,0
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2,1,Aston Villa,...,4-3-3,Robert Jones,Match Report,NaN,22,8,16.3,1.0,0,0

In [20]:
years = list(range(2023, 2000, -1))
all_matches = []

In [21]:
standings_url = "https://fbref.com/en/comps/9/Premier-League-Stats"

In [22]:
import time
for year in years:
    data = requests.get(standings_url)
    soup = BeautifulSoup(data.text)
    standings_table = soup.select('table.stats_table')[0]

    links = [l.get("href") for l in standings_table.find_all('a')]
    links = [l for l in links if '/squads/' in l]
    team_urls = [f"https://fbref.com{l}" for l in links]
    
    previous_season = soup.select("a.prev")[0].get("href")
    standings_url = f"https://fbref.com{previous_season}"
    
    for team_url in team_urls:
        team_name = team_url.split("/")[-1].replace("-Stats", "").replace("-", " ")
        data = requests.get(team_url)
        matches = pd.read_html(data.text, match="Scores & Fixtures")[0]
        soup = BeautifulSoup(data.text)
        links = [l.get("href") for l in soup.find_all('a')]
        links = [l for l in links if l and 'all_comps/shooting/' in l]
        data = requests.get(f"https://fbref.com{links[0]}")
        shooting = pd.read_html(data.text, match="Shooting")[0]
        shooting.columns = shooting.columns.droplevel()
        try:
            team_data = matches.merge(shooting[["Date", "Sh", "SoT", "Dist", "PK", "PKatt"]], on="Date")
        except ValueError:
            continue
        team_data = team_data[team_data["Comp"] == "Premier League"]
        
        team_data["Season"] = year
        team_data["Team"] = team_name
        all_matches.append(team_data)
        time.sleep(1)

In [23]:
len(all_matches)

460

In [26]:
match_df = pd.concat(all_matches)
match_df.columns = [c.lower() for c in match_df.columns]
match_df

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,referee,match report,notes,sh,sot,dist,pk,pkatt,season,team
0,2022-08-05,20:00,Premier League,Matchweek 1,Fri,Away,W,2,0,Crystal Palace,...,Anthony Taylor,Match Report,NaN,10.0,2.0,14.6,0.0,0.0,2023,Arsenal
1,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,2,Leicester City,...,Darren England,Match Report,NaN,19.0,7.0,13.0,0.0,0.0,2023,Arsenal
2,2022-08-20,17:30,Premier League,Matchweek 3,Sat,Away,W,3,0,Bournemouth,...,Craig Pawson,Match Report,NaN,14.0,6.0,14.8,0.0,0.0,2023,Arsenal
3,2022-08-27,17:30,Premier League,Matchweek 4,Sat,Home,W,2,1,Fulham,...,Jarred Gillett,Match Report,NaN,22.0,8.0,15.5,0.0,0.0,2023,Arsenal
4,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,2,1,Aston Villa,...,Robert Jones,Match Report,NaN,22.0,8.0,16.3,0.0,0.0,2023,Arsenal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33,2001-04-28,NaN,Premier League,Matchweek 36,Sat,Away,L,1,2,Everton,...,Paul Durkin,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
34,2001-05-01,NaN,Premier League,Matchweek 21,Tue,Home,L,0,2,Liverpool,...,Jeff Winter,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
35,2001-05-05,NaN,Premier League,Matchweek 37,Sat,Home,D,1,1,Middlesbrough,...,Graham Barber,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
36,2001-05-13,NaN,Premier League,Matchweek 34,Sun,Away,L,1,6,Leeds United,...,Andy D'Urso,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
37,2001-05-19,NaN,Premier League,Matchweek 38,Sat,Away,D,0,0,Coventry City,...,Alan Wiley,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City

In [27]:
match_df.to_csv("matches1.csv")

In [28]:
match_df.shape

(17308, 26)

In [29]:
match_df.tail()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,referee,match report,notes,sh,sot,dist,pk,pkatt,season,team
33,2001-04-28,NaN,Premier League,Matchweek 36,Sat,Away,L,1,2,Everton,...,Paul Durkin,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
34,2001-05-01,NaN,Premier League,Matchweek 21,Tue,Home,L,0,2,Liverpool,...,Jeff Winter,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
35,2001-05-05,NaN,Premier League,Matchweek 37,Sat,Home,D,1,1,Middlesbrough,...,Graham Barber,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
36,2001-05-13,NaN,Premier League,Matchweek 34,Sun,Away,L,1,6,Leeds United,...,Andy D'Urso,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
37,2001-05-19,NaN,Premier League,Matchweek 38,Sat,Away,D,0,0,Coventry City,...,Alan Wiley,Match Report,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City

In [36]:
match_df.drop(['notes', 'referee', 'match report', 'formation'], 1).tail()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,poss,attendance,captain,sh,sot,dist,pk,pkatt,season,team
33,2001-04-28,NaN,Premier League,Matchweek 36,Sat,Away,L,1,2,Everton,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
34,2001-05-01,NaN,Premier League,Matchweek 21,Tue,Home,L,0,2,Liverpool,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
35,2001-05-05,NaN,Premier League,Matchweek 37,Sat,Home,D,1,1,Middlesbrough,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
36,2001-05-13,NaN,Premier League,Matchweek 34,Sun,Away,L,1,6,Leeds United,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City
37,2001-05-19,NaN,Premier League,Matchweek 38,Sat,Away,D,0,0,Coventry City,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,2001,Bradford City

In [37]:
match_df['team'].value_counts()

Tottenham Hotspur           866
Everton                     866
Chelsea                     866
Arsenal                     865
Manchester United           865
Liverpool                   864
Manchester City             827
Newcastle United            789
Aston Villa                 752
West Ham United             751
Southampton                 600
Fulham                      599
Sunderland                  532
West Bromwich Albion        494
Leicester City              448
Bolton Wanderers            418
Blackburn Rovers            418
Crystal Palace              409
Middlesbrough               380
Stoke City                  380
Wolverhampton Wanderers     334
Wigan Athletic              304
Burnley                     304
Portsmouth                  266
Charlton Athletic           266
Birmingham City             266
Norwich City                266
Watford                     266
Swansea City                266
Leeds United                257
Bournemouth                 220
Brighton and Hove Albion    218
Hull City                   190
Reading                     114
Sheffield United            114
Queens Park Rangers         114
Derby County                114
Huddersfield Town            76
Ipswich Town                 76
Cardiff City                 76
Brentford                    68
Bradford City                38
Coventry City                38
Blackpool                    38
Nottingham Forest            30
Name: team, dtype: int64

In [42]:
match_df['round'].value_counts()

Matchweek 19    460
Matchweek 20    460
Matchweek 23    460
Matchweek 8     460
Matchweek 14    460
Matchweek 9     460
Matchweek 24    460
Matchweek 13    460
Matchweek 6     460
Matchweek 2     460
Matchweek 27    460
Matchweek 18    460
Matchweek 7     460
Matchweek 22    460
Matchweek 12    460
Matchweek 16    460
Matchweek 1     460
Matchweek 5     460
Matchweek 21    460
Matchweek 11    460
Matchweek 26    460
Matchweek 3     460
Matchweek 4     460
Matchweek 15    460
Matchweek 10    460
Matchweek 29    460
Matchweek 17    460
Matchweek 25    458
Matchweek 30    456
Matchweek 28    454
Matchweek 37    440
Matchweek 35    440
Matchweek 36    440
Matchweek 33    440
Matchweek 32    440
Matchweek 38    440
Matchweek 34    440
Matchweek 31    440
Name: round, dtype: int64